use microblog;

DROP TABLE IF EXISTS Collection;
DROP TABLE IF EXISTS CommentLike;
DROP TABLE IF EXISTS BlogLike;
DROP TABLE IF EXISTS BlogLabel;
DROP TABLE IF EXISTS BlogCategory;
DROP TABLE IF EXISTS Comment;
DROP TABLE IF EXISTS Blog;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Follow;
DROP TABLE IF EXISTS User;
